### ISSUE TITLE
Relacionar Curso y RegistroAsistencia

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/2024_gc_p3_g5_sf#20]
**Título:** Implementar relación One-to-Many entre `Curso` y `RegistroAsistencia`

**Descripción:**

1. Establecer una relación One-to-Many entre la entidad `Curso` y `RegistroAsistencia`.
2. Añadir las anotaciones necesarias en ambas entidades para representar esta relación.
3. Eliminar los constructores, las anotaciones `@Table` y `@Column` innecesarias o redundantes.
4. Enviar un pull request con los cambios realizados y adjuntar una imagen del resultado del diagrama de base de datos.

**Comment by BalmacedaIvan** [comment]
![relacion](https://github.com/ahumadamob/2024_gc_p3_g5_sf/assets/79170983/792d9c6c-a0b5-48bf-9cf3-29720239e6a6)
